export const GET_TRAVELPACKAGES = "GET_TRAVELPACKAGES";
export const TRAVELPACKAGES_LOADING = "TRAVELPACKAGES_LOADING";
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const CHECKOUT = "CHECKOUT";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
